import {
  Controller,
  Get,
  Post,
  Put,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiQuery } from '@nestjs/swagger';
import { AdminService } from './admin.service';
import { CreateTechnicianDto } from './dto/create-technician.dto';
import { UpdateTechnicianDto } from './dto/update-technician.dto';

@ApiTags('Admin Console')
@Controller('admin')
export class AdminController {
  constructor(private readonly adminService: AdminService) {}

  @Post('technician')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Create a new technician account with autogenerated credentials' })
  @ApiResponse({ status: 201, description: 'Technician created successfully' })
  async createTechnician(@Body() dto: CreateTechnicianDto) {
    return this.adminService.createTechnician(dto);
  }

  @Get('technicians')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'List and filter active technicians' })
  @ApiQuery({ name: 'search', required: false, type: String })
  @ApiQuery({ name: 'branch', required: false, type: String })
  @ApiQuery({ name: 'isActive', required: false, type: String })
  async listTechnicians(
    @Query('search') search?: string,
    @Query('branch') branch?: string,
    @Query('isActive') isActive?: string,
  ) {
    return this.adminService.listTechnicians(search, branch, isActive);
  }

  @Put('technician/:id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Update technician profiles' })
  @ApiResponse({ status: 200, description: 'Technician updated successfully' })
  async updateTechnician(@Param('id') id: string, @Body() dto: UpdateTechnicianDto) {
    return this.adminService.updateTechnician(id, dto);
  }

  @Patch('technician/:id/status')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Enable or disable a technician account' })
  async toggleStatus(@Param('id') id: string, @Body('isActive') isActive: boolean) {
    return this.adminService.toggleStatus(id, isActive);
  }

  @Post('technician/:id/reset-password')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Reset password for a technician account' })
  async resetPassword(@Param('id') id: string) {
    return this.adminService.resetPassword(id);
  }

  @Delete('technician/:id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Soft delete a technician account' })
  async softDelete(@Param('id') id: string) {
    return this.adminService.softDelete(id);
  }

  @Get('dashboard/stats')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Retrieve system dashboard stats for the administrative portal' })
  async getDashboardStats() {
    return this.adminService.getDashboardStats();
  }

  // Booking admin routes
  @Get('bookings')
  async listBookingsAdmin(
    @Query('search') search?: string,
    @Query('status') status?: string,
    @Query('priority') priority?: string,
    @Query('customerId') customerId?: string,
    @Query('technicianId') technicianId?: string,
    @Query('startDate') startDate?: string,
    @Query('endDate') endDate?: string,
    @Query('sortBy') sortBy?: string,
    @Query('sortOrder') sortOrder?: string,
    @Query('page') page?: string,
    @Query('limit') limit?: string,
  ) {
    return this.adminService.listBookingsAdmin(
      search,
      status,
      priority,
      customerId,
      technicianId,
      startDate,
      endDate,
      sortBy,
      sortOrder,
      page ? parseInt(page, 10) : 1,
      limit ? parseInt(limit, 10) : 10,
    );
  }

  @Get('bookings/:id')
  async getBookingDetailsAdmin(@Param('id') id: string) {
    return this.adminService.getBookingDetailsAdmin(id);
  }

  @Put('bookings/:id')
  async updateBookingAdmin(@Param('id') id: string, @Body() dto: any) {
    return this.adminService.updateBookingAdmin(id, dto);
  }

  // Customer admin routes
  @Get('customers')
  async listCustomers(
    @Query('search') search?: string,
    @Query('isActive') isActive?: string,
    @Query('isVip') isVip?: string,
    @Query('sortBy') sortBy?: string,
    @Query('sortOrder') sortOrder?: string,
    @Query('page') page?: string,
    @Query('limit') limit?: string,
  ) {
    return this.adminService.listCustomers(
      search,
      isActive,
      isVip,
      sortBy,
      sortOrder,
      page ? parseInt(page, 10) : 1,
      limit ? parseInt(limit, 10) : 10,
    );
  }

  @Get('customers/:id')
  async getCustomerDetails(@Param('id') id: string) {
    return this.adminService.getCustomerDetails(id);
  }

  @Put('customers/:id')
  async updateCustomer(@Param('id') id: string, @Body() dto: any) {
    return this.adminService.updateCustomer(id, dto);
  }

  @Patch('customers/:id/status')
  async toggleCustomerStatus(@Param('id') id: string, @Body('isActive') isActive: boolean) {
    return this.adminService.toggleCustomerStatus(id, isActive);
  }

  @Delete('customers/:id')
  async softDeleteCustomer(@Param('id') id: string) {
    return this.adminService.softDeleteCustomer(id);
  }

  // Services Catalog CRUD
  @Post('services/categories')
  async createCategory(@Body() dto: any) {
    return this.adminService.createCategory(dto);
  }

  @Put('services/categories/:id')
  async updateCategory(@Param('id') id: string, @Body() dto: any) {
    return this.adminService.updateCategory(id, dto);
  }

  @Delete('services/categories/:id')
  async deleteCategory(@Param('id') id: string) {
    return this.adminService.deleteCategory(id);
  }

  @Post('services/items')
  async createServiceItem(@Body() dto: any) {
    return this.adminService.createServiceItem(dto);
  }

  @Put('services/items/:id')
  async updateServiceItem(@Param('id') id: string, @Body() dto: any) {
    return this.adminService.updateServiceItem(id, dto);
  }

  @Delete('services/items/:id')
  async deleteServiceItem(@Param('id') id: string) {
    return this.adminService.deleteServiceItem(id);
  }

  // Payments / Revenue
  @Get('payments/stats')
  async getPaymentStats() {
    return this.adminService.getPaymentStats();
  }

  @Get('payments/history')
  async getPaymentHistory(
    @Query('page') page?: string,
    @Query('limit') limit?: string,
  ) {
    return this.adminService.getPaymentHistory(
      page ? parseInt(page, 10) : 1,
      limit ? parseInt(limit, 10) : 10,
    );
  }

  // Analytics
  @Get('analytics')
  async getAnalytics() {
    return this.adminService.getAnalytics();
  }

  // Reports
  @Get('reports/generate')
  async generateReport(
    @Query('type') type: string,
    @Query('format') format: string,
    @Query('startDate') startDate?: string,
    @Query('endDate') endDate?: string,
  ) {
    return this.adminService.generateReport(type, format, startDate, endDate);
  }

  // System Logs
  @Get('logs')
  async getLogs(
    @Query('search') search?: string,
    @Query('action') action?: string,
    @Query('page') page?: string,
    @Query('limit') limit?: string,
  ) {
    return this.adminService.getLogs(
      search,
      action,
      page ? parseInt(page, 10) : 1,
      limit ? parseInt(limit, 10) : 50,
    );
  }

  // Settings
  @Get('settings')
  async getSettings() {
    return this.adminService.getSettings();
  }

  @Put('settings')
  async updateSettings(@Body() dto: any) {
    return this.adminService.updateSettings(dto);
  }

  // Notifications
  @Get('notifications')
  async getNotifications() {
    return this.adminService.getNotifications();
  }

  @Patch('notifications/:id/read')
  async markNotificationRead(@Param('id') id: string) {
    return this.adminService.markNotificationRead(id);
  }

  @Delete('notifications/:id')
  async deleteNotification(@Param('id') id: string) {
    return this.adminService.deleteNotification(id);
  }
}

