// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZGnAxMFObH-d6ZSUT7HjdqQO7ECh7tk',
    appId: '1:833719706774:web:e0b61551857aab61380eb7',
    messagingSenderId: '833719706774',
    projectId: 'asp1-4a07f',
    authDomain: 'asp1-4a07f.firebaseapp.com',
    storageBucket: 'asp1-4a07f.firebasestorage.app',
    measurementId: 'G-7WBGHYWXZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC203yin9oViClVSKgr3syPBpd11xHCs-s',
    appId: '1:833719706774:android:051f33b4821c4561380eb7',
    messagingSenderId: '833719706774',
    projectId: 'asp1-4a07f',
    storageBucket: 'asp1-4a07f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgE2V4TZuJ866qa43y83hke7WFcnbj4k',
    appId: '1:833719706774:ios:5ebb62d42249f701380eb7',
    messagingSenderId: '833719706774',
    projectId: 'asp1-4a07f',
    storageBucket: 'asp1-4a07f.firebasestorage.app',
    iosBundleId: 'com.example.projectPhoenixCustomer',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgE2V4TZuJ866qa43y83hke7WFcnbj4k',
    appId: '1:833719706774:ios:5ebb62d42249f701380eb7',
    messagingSenderId: '833719706774',
    projectId: 'asp1-4a07f',
    storageBucket: 'asp1-4a07f.firebasestorage.app',
    iosBundleId: 'com.example.projectPhoenixCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZGnAxMFObH-d6ZSUT7HjdqQO7ECh7tk',
    appId: '1:833719706774:web:06e291e0d3df9e05380eb7',
    messagingSenderId: '833719706774',
    projectId: 'asp1-4a07f',
    authDomain: 'asp1-4a07f.firebaseapp.com',
    storageBucket: 'asp1-4a07f.firebasestorage.app',
    measurementId: 'G-YSF8SDDBRC',
  );
}
